FROM jenkins/jenkins:lts-centos

ARG JENKINS_ADMIN_USER=${JENKINS_ADMIN_USER}
ARG JENKINS_ADMIN_USER_PASSWORD=${JENKINS_ADMIN_USER_PASSWORD}

ENV JENKINS_USER $JENKINS_ADMIN_USER
ENV JENKINS_PASS $JENKINS_ADMIN_USER_PASSWORD


